crm/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from leads.views import landing_page, LandingPageView, SignupView

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('leads/', include('leads.urls', namespace='leads')),
    path('agents/', include('agents.urls', namespace='agents')),
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('reset-password/', PasswordResetView.as_view(), name="reset-password"),
    path('password-reset-done/', PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from . import views

app_name = "leads"

urlpatterns = [
    path('', views.LeadListView.as_view(), name='lead-list'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name='lead-detail'),
    path('<int:pk>/update/', views.LeadUpdateView.as_view(), name='lead-update'),
    path('<int:pk>/delete/', views.LeadDeletView.as_view(), name="lead-delete"),
    path('<int:pk>/assign-agent/',
         views.AssignAgentView.as_view(), name="assign-agent"),
    path('<int:pk>/category/',
         views.LeadCategoryUpdateView.as_view(), name="lead-category-update"),
    path('create/', views.LeadCreateView.as_view(), name="lead-create"),
    path('categories/', views.CategoryListView.as_view(), name="category-list"),
    path('category/<int:pk>/', views.CategoryDetailView.as_view(),
         name="category-detail"),
]

leads/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    is_organizer = models.BooleanField(default=True)
    is_agent = models.BooleanField(default=False)


class UserProfile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.user.username


class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organization = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Lead(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    age = models.IntegerField(default=0)
    organization = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    agent = models.ForeignKey(
        Agent, null=True, blank=True, on_delete=models.SET_NULL)
    category = models.ForeignKey(
        'Category', on_delete=models.SET_NULL, blank=True, null=True)

    description = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    phone_number = models.CharField(max_length=20)
    email = models.EmailField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Category(models.Model):
    # New, Contacted, Converted, Unconverted
    name = models.CharField(max_length=30)
    organization = models.ForeignKey(
        UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"


def post_user_created_signal(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)


post_save.connect(post_user_created_signal, sender=User)

leads/forms.py
from django.contrib.auth import get_user_model
from django import forms
from .models import Lead, Agent
from django.contrib.auth.forms import UserCreationForm, UsernameField

User = get_user_model()


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username",)
        field_classes = {'username': UsernameField}


class LeadForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    age = forms.IntegerField(min_value=0)


class LeadModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            'first_name',
            'last_name',
            'age',
            'agent',
            'description',
            'phone_number',
            'email',
        )


class AssignAgentForm(forms.Form):
    # agent = forms.ChoiceField(choices=(
    #     ('Agent 1', 'Agent 1 Full Name'),
    #     ('Agent 2', 'Agent 2 Full Name'),
    # ))
    agent = forms.ModelChoiceField(queryset=Agent.objects.none())

    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request")
        agents = Agent.objects.filter(organization=request.user.userprofile)
        super(AssignAgentForm, self).__init__(*args, **kwargs)
        self.fields["agent"].queryset = agents


class LeadCategoryUpdateForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            "category",
        )

leads/views.py
from typing import Any
from django.db import models
from django.db.models.query import QuerySet
from django.forms.models import BaseModelForm
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.urls import reverse
from django.views import generic
from django.core.mail import send_mail
from django.template import loader

from agents.mixins import LoginRequiredAndOrganizerMixin
from .models import Lead, Agent, Category
from .forms import LeadForm, LeadModelForm, CustomUserCreationForm, AssignAgentForm, LeadCategoryUpdateForm


class SignupView(generic.CreateView):
    template_name = "registration/signup.html"
    form_class = CustomUserCreationForm

    def get_success_url(self):
        return reverse("login")


class LandingPageView(generic.TemplateView):
    template_name = "landing.html"


def landing_page(request):
    return render(request, "landing.html")


class LeadListView(LoginRequiredMixin, generic.ListView):
    template_name = "leads/lead_list.html"
    context_object_name = "leads"  # object_list is default context_object_name

    def get_queryset(self):
        user = self.request.user
        # Initial queryset of leads for the entire organization
        if user.is_organizer:
            queryset = Lead.objects.filter(
                organization=user.userprofile, agent__isnull=False)
        else:
            queryset = Lead.objects.filter(
                organization=user.agent.organization, agent__isnull=False)
            # filter for the agent that is logged in
            queryset = queryset.filter(agent__user=user)
        return queryset

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super(LeadListView, self).get_context_data(**kwargs)
        if user.is_organizer:
            queryset = Lead.objects.filter(
                organization=user.userprofile, agent__isnull=True)
            context.update({
                'unassigned_leads': queryset
            })
        return context


def lead_list(request):
    leads = Lead.objects.all()
    context = {
        "leads": leads
    }
    return render(request, "leads/lead_list.html", context)


class LeadDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "leads/lead_detail.html"
    queryset = Lead.objects.all()
    context_object_name = "lead"

    def get_queryset(self):
        user = self.request.user
        queryset = Lead.objects.all()
        if user.is_organizer:
            queryset = queryset.filter(organization=user.userprofile)
        else:
            queryset = Lead.objects.filter(
                organization=user.agent.organization)
            queryset.filter(agent__user=user)
        return queryset


def lead_detail(request, pk):
    lead = Lead.objects.get(pk=pk)
    context = {
        'lead': lead
    }
    return render(request, "leads/lead_detail.html", context)


class LeadCreateView(LoginRequiredAndOrganizerMixin, generic.CreateView):
    template_name = "leads/lead_create.html"
    form_class = LeadModelForm

    def get_success_url(self) -> str:
        return reverse("leads:lead-detail", args=(self.object.pk,))

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        lead = form.save(commit=False)
        lead.organization = self.request.user.userprofile
        lead.save()
        html_message = loader.render_to_string(
            'leads/email_template.html',
            {
                'username': "admin",
                'subject': "Lead with was created successfully."
            }
        )
        send_mail(
            subject="A lead has been created",
            message="Go to the site to see the new lead",
            from_email="admin@crm.com",
            recipient_list=["test@test.com"],
            html_message=html_message
        )
        return super(LeadCreateView, self).form_valid(form)


def lead_create(request):
    form = LeadModelForm()
    if request.method == "POST":
        form = LeadModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/leads")
    context = {
        "form": form
    }
    return render(request, "leads/lead_create.html", context)


class LeadUpdateView(LoginRequiredAndOrganizerMixin, generic.UpdateView):
    template_name = "leads/lead_update.html"
    form_class = LeadModelForm

    def get_success_url(self) -> str:
        return reverse("leads:lead-detail", args=(self.object.pk,))

    def get_queryset(self):
        user = self.request.user
        if user.is_organizer:
            queryset = Lead.objects.filter(organization=user.userprofile)
        return queryset


def lead_update(request, pk):
    lead = Lead.objects.get(pk=pk)
    form = LeadModelForm(instance=lead)
    if request.method == 'POST':
        form = LeadModelForm(request.POST, instance=lead)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('leads:lead-detail', args=(lead.pk,)))
    context = {
        'lead': lead,
        'form': form
    }
    return render(request, 'leads/lead_update.html', context)


class LeadDeletView(LoginRequiredAndOrganizerMixin, generic.DeleteView):
    template_name = "leads/lead_delete.html"
    # queryset = Lead.objects.all()

    def get_success_url(self):
        return reverse("leads:lead-list")

    def get_queryset(self):
        user = self.request.user
        if user.is_organizer:
            queryset = Lead.objects.filter(organization=user.userprofile)
        return queryset


def lead_delete(request, pk):
    lead = Lead.objects.get(pk=pk)
    lead.delete()
    return redirect("/leads")


class AssignAgentView(LoginRequiredAndOrganizerMixin, generic.FormView):
    template_name = "leads/assign_agent.html"
    form_class = AssignAgentForm

    def get_form_kwargs(self, **kwargs):
        kwargs = super(AssignAgentView, self).get_form_kwargs(**kwargs)
        kwargs.update({
            "request": self.request
        })
        return kwargs

    def get_success_url(self):
        return reverse("leads:lead-list")

    def form_valid(self, form):
        print(form.data)
        agent = form.cleaned_data["agent"]
        lead = Lead.objects.get(id=self.kwargs["pk"])
        lead.agent = agent
        lead.save()
        return super(AssignAgentView, self).form_valid(form)


class CategoryListView(LoginRequiredMixin, generic.ListView):
    template_name = 'leads/category_list.html'
    context_object_name = 'category_list'

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        user = self.request.user
        if user.is_organizer:
            queryset = Lead.objects.filter(organization=user.userprofile)
        else:
            queryset = Lead.objects.filter(
                organization=user.agent.organization)
        context.update({
            'unassigned_lead_count': queryset.filter(category__isnull=True).count()
        })

        return context

    def get_queryset(self):
        user = self.request.user
        if user.is_organizer:
            queryset = Category.objects.filter(organization=user.userprofile)
        else:
            queryset = Category.objects.filter(
                organization=user.agent.organization)
        return queryset


class CategoryDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "leads/category_detail.html"
    context_object_name = "category"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        leads = self.get_object().lead_set.all()
        context.update({
            "leads": leads
        })
        return context

    def get_queryset(self):
        user = self.request.user
        if user.is_organizer:
            queryset = Category.objects.filter(organization=user.userprofile)
        else:
            queryset = Category.objects.filter(
                organization=user.agent.organization)
        return queryset


class LeadCategoryUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name = "leads/lead_category_update.html"
    form_class = LeadCategoryUpdateForm

    def get_queryset(self):
        user = self.request.user

        if user.is_organizer:
            queryset = Lead.objects.filter(organization=user.userprofile)
        else:
            queryset = Lead.objects.filter(
                organization=user.agent.organization)
        return queryset

    def get_success_url(self):
        return reverse("leads:lead-detail", args=(self.object.pk,))

# def lead_update(request, pk):
#     lead = Lead.objects.get(pk=pk)
#     form = LeadForm()
#     if request.method == 'POST':
#         form = LeadForm(request.POST)
#         if form.is_valid():
#             first_name = form.cleaned_data['first_name']
#             last_name = form.cleaned_data['last_name']
#             age = form.cleaned_data['age']
#             lead.first_name = first_name
#             lead.last_name = last_name
#             lead.age = age
#             lead.save()
#             # return redirect('leads:detail', args=(lead.pk,))
#             return HttpResponseRedirect(reverse('leads:detail', args=(lead.pk,)))
#     context = {
#         'lead': lead,
#         'form': form
#     }
#     return render(request, "leads/lead_update.html", context)


# def lead_create(request):
#     form = LeadForm()
#     if request.method == "POST":
#         form = LeadForm(request.POST)
#         if form.is_valid():
#             first_name = form.cleaned_data['first_name']
#             last_name = form.cleaned_data['last_name']
#             age = form.cleaned_data['age']
#             agent = Agent.objects.first()
#             Lead.objects.create(
#                 first_name=first_name,
#                 last_name=last_name,
#                 age=age,

leads/templates/leads/assign_agent.html
{% extends 'base.html' %} {% block title %} Create New Lead {% endblock title %}
<!-- Content -->
{% block content %}
<a href="{% url 'leads:lead-list' %}">Go back to leads</a>
<hr />
<h2>Assign an agent to this lead</h2>
<form action="." method="post">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit">Submit</button>
</form>
{% endblock content %}

leads/templates/leads/category_list.html
{% extends 'base.html' %}
<!-- Content -->
{% block content %}

<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-col text-center w-full mb-20">
      <h1
        class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900"
      >
        Categories
      </h1>
      <p class="lg:w-2/3 mx-auto leading-relaxed text-base">
        These categories segment the leads.
      </p>
    </div>
    <div class="lg:w-2/3 w-full mx-auto overflow-auto">
      <table class="table-auto w-full text-left whitespace-no-wrap">
        <thead>
          <tr>
            <th
              class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl"
            >
              Name
            </th>
            <th
              class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100"
            >
              Lead Count
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="px-4 py-3">UNASSIGNED</td>
            <td class="px-4 py-3">{{ unassigned_lead_count }}</td>
          </tr>
          {% for category in category_list %}
          <tr>
            <td class="px-4 py-3">
              <a href="{% url 'leads:category-detail' pk=category.pk %}"
                >{{ category.name }}</a
              >
            </td>
            <td class="px-4 py-3">{{ category.lead_set.count }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</section>
{% endblock content %}

leads/templates/leads/email_template.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Email Created</title>
  </head>
  <body>
    <h1>{{ username }}</h1>
    <h2>{{ subject }}</h2>
  </body>
</html>

leads/templates/leads/lead_category_update.html
{% extends 'base.html' %} {% load tailwind_filters %} {% block title %} Update
{% endblock title %}
<!-- Content -->
{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
          {{ lead.first_name }} {{ lead.last_name}}
        </h1>
        <div class="flex mb-4">
          <a
            href="{% url 'leads:lead-detail' lead.pk %}"
            class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"
            >Overview</a
          >
          <a
            class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1"
            >Category</a
          >
          <a
            href="{% url 'leads:lead-update' lead.id %}"
            class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"
            >Update lead</a
          >
        </div>

        <form action="." method="post">
          {% csrf_token %} {{ form|crispy }}
          <button
            type="submit"
            class="w-full bg-blue-500 hover:bg-blue-600 px-3 py-1 rounded-md text-white"
          >
            Update
          </button>
        </form>
      </div>
      <img
        alt="ecommerce"
        class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded"
        src="https://dummyimage.com/400x400"
      />
    </div>
  </div>
</section>
{% endblock content %}

leads/templates/leads/lead_detail.html
{% extends 'base.html' %} {% block title %} {{lead.first_name}} Details
{%endblock title %} {% block content %}

<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
          {{ lead.first_name }} {{ lead.last_name}}
        </h1>
        <div class="flex mb-4">
          <a
            class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1"
            >Overview</a
          >
          <a
            href="{% url 'leads:lead-category-update' lead.pk %}"
            class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"
            >Category</a
          >
          <a
            href="{% url 'leads:lead-update' lead.id %}"
            class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"
            >Update lead</a
          >
        </div>
        <p class="leading-relaxed mb-4">{{ lead.description }}</p>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Age</span>
          <span class="ml-auto text-gray-900">{{ lead.age }}</span>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Email</span>
          <span class="ml-auto text-gray-900">{{ lead.email }}</span>
        </div>
        <div class="flex border-t border-b mb-6 border-gray-200 py-2">
          <span class="text-gray-500">Phone Number</span>
          <span class="ml-auto text-gray-900">{{ lead.phone_number }}</span>
        </div>
        <div class="flex">
          <a
            href="{% url 'leads:lead-delete' lead.id %}"
            class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded"
          >
            Delete
          </a>
          <button
            class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4"
          >
            <svg
              fill="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              class="w-5 h-5"
              viewBox="0 0 24 24"
            >
              <path
                d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"
              ></path>
            </svg>
          </button>
        </div>
      </div>
      <img
        alt="ecommerce"
        class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded"
        src="https://dummyimage.com/400x400"
      />
    </div>
  </div>
</section>

{% endblock content %}

leads/templates/leads/lead_list.html
{% extends 'base.html' %} {% block title %} Lead List {% endblock title %}

<!-- CONTENT -->
{%block content %}
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
    <div
      class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200"
    >
      <div>
        <h1 class="text-4xl text-gray-800">Leads</h1>
      </div>
      <div>
        <a class="hover:text-blue-500" href="{% url 'leads:category-list' %}"
          >View categories</a
        >
      </div>
      <div class="">
        {% if request.user.is_organizer%}
        <a
          class="text-gray-500 hover:text-blue-500"
          href="{% url 'leads:lead-create' %}"
          >Create a new lead</a
        >
        {% endif %}
      </div>
    </div>

    <div class="flex flex-wrap -m-4">
      {% for lead in leads %}
      <div class="p-4 lg:w-1/2 md:w-full">
        <div
          class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col"
        >
          <div
            class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0"
          >
            <svg
              fill="none"
              stroke="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              class="w-8 h-8"
              viewBox="0 0 24 24"
            >
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
              {{ lead.first_name }} {{lead.last_name}}
            </h2>
            <p class="leading-relaxed text-base">{{ lead.description }}</p>
            <a
              href="{% url 'leads:lead-detail' lead.id %}"
              class="mt-3 text-indigo-500 inline-flex items-center"
              >View lead
              <svg
                fill="none"
                stroke="currentColor"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                class="w-4 h-4 ml-2"
                viewBox="0 0 24 24"
              >
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    <hr />
    {% if unassigned_leads.exists %}
    <div>
      <h1 class="mt-5 text-4xl text-gray-800">Unassigned Leads</h1>
    </div>
    <div class="flex flex-wrap -m-4">
      {% for lead in unassigned_leads %}
      <div class="p-4 lg:w-1/2 md:w-full">
        <div
          class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col"
        >
          <div
            class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0"
          >
            <svg
              fill="none"
              stroke="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              class="w-8 h-8"
              viewBox="0 0 24 24"
            >
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
              {{ lead.first_name }} {{lead.last_name}}
            </h2>
            <p class="leading-relaxed text-base">{{ lead.description }}</p>
            <a
              href="{% url 'leads:assign-agent' lead.pk %}"
              class="mt-3 text-indigo-500 inline-flex items-center"
              >Assign an agent
              <svg
                fill="none"
                stroke="currentColor"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                class="w-4 h-4 ml-2"
                viewBox="0 0 24 24"
              >
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    {% endif %}
  </div>
</section>

{% endblock content %}

leads/templates/leads/lead_update.html
{% extends 'base.html' %} {% load tailwind_filters %}
<!-- Title -->
{% block title %} Update {% endblock title %}
<!-- Content -->
{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
          {{ lead.first_name }} {{ lead.last_name}}
        </h1>
        <div class="flex mb-4">
          <a
            href="{% url 'leads:lead-detail' lead.pk %}"
            class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"
            >Overview</a
          >
          <a
            href="{% url 'leads:lead-category-update' lead.pk %}"
            class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"
            >Category</a
          >
          <a
            href="{% url 'leads:lead-update' lead.id %}"
            class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1"
            >Update lead</a
          >
        </div>

        <form action="." method="post">
          {% csrf_token %} {{ form|crispy }}
          <button
            type="submit"
            class="w-full bg-blue-500 hover:bg-blue-600 px-3 py-1 rounded-md text-white"
          >
            Update
          </button>
        </form>
        <div class="mt-5 py-5 border-t border-gray-200">
          <a
            href="{% url 'leads:lead-delete' lead.id %}"
            class="mt-3 w-1/2 text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded"
          >
            Delete
          </a>
        </div>
      </div>
      <img
        alt="ecommerce"
        class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded"
        src="https://dummyimage.com/400x400"
      />
    </div>
  </div>
</section>
{% endblock content %}